import { createContext, useContext, useEffect, useMemo, useState } from "react";
import { languageStorageKey, saveLanguagePreference } from "./languagePreference";

export type SiteLanguage = "en" | "ar" | "zh-CN" | "zh-TW";
export const siteLanguageOptions: { code: SiteLanguage; label: string }[] = [
  { code: "en", label: "English" },
  { code: "ar", label: "العربية — Arabic" },
  { code: "zh-CN", label: "中文（简体）— Chinese, Simplified" },
  { code: "zh-TW", label: "中文（繁體）— Chinese, Traditional" },
];

const english: Record<string, string> = {
  pageTitle: "Under Progress — The web should adapt to people", pageDescription: "Under Progress is a consent-first student accessibility companion that helps students make the web easier to read, understand, and focus on.", navHow: "How it works", navSupport: "Student support", navExtension: "Extension", navProject: "Support", chooseTools: "Choose your tools", createProfile: "Create your profile", exploreJourney: "Explore the journey", dark: "Dark", light: "Light", useDark: "Use dark mode", useLight: "Use light mode", back: "Back",
  heroKicker: "Consent-first student accessibility companion", heroTitle: "Make learning easier to meet.", heroBody: "Under Progress helps students describe what supports them, learn in an accessible environment, and reach the right human support—while carrying their chosen tools beyond the classroom.", heroNote: "Your choices stay yours · Support, not diagnosis",
  howKicker: "How it works", howTitle: "Your choices follow you.", howBody: "Your profile starts with a clear sample preview, becomes a saved accessibility preset, and can be used outside the learning space through the extension.", chooseSupport: "Choose support", chooseSupportBody: "Select one or more support needs in a compact list built for phones as well as desktops.", seeSample: "See a sample", seeSampleBody: "Text scale, spacing, contrast, and focus update in a stable sample reading area.", saveDefault: "Save a default", saveDefaultBody: "Keep one starting point for future sessions and change it whenever life changes.", reachSupport: "Reach support", reachSupportBody: "Use the extension for practical tools and request human guidance when you choose.",
  coreKicker: "The core experience", coreTitle: "Learn with support, on your terms.", coreBody: "Under Progress is the learning and support experience—not just a font-changing extension. It is designed for students to choose useful tools, reflect on what is working, and decide whether to seek human Student Accessibility Services (SAS) guidance.", coreNote: "No automatic referrals. No diagnostic claims. No action without the student’s consent.", learn: "Learn", learnTitle: "Accessible learning tools", learnBody: "Students use the reading, focus, contrast, and listening settings that help them engage with learning material.", checkIn: "Check in", checkTitle: "Optional reflection", checkBody: "Short check-ins help a student notice what is helping and update their selected supports over time.", connect: "Connect", connectTitle: "Human support by choice", connectBody: "When they are ready, a student can choose to request SAS guidance. A person—not an algorithm—provides the support.",
  beyondKicker: "Beyond text", beyondTitle: "A clear path that does not depend on reading.", beyondBody: "Under Progress is being shaped for students who cannot, or prefer not to, rely on a text-heavy form. The support journey should be usable through listening, visual cues, and a human route—not only through written instructions.", voiceTitle: "Voice-first guidance", voiceBody: "Simple prompts and learning content can be heard aloud instead of read alone.", iconTitle: "Icon-led choices", iconBody: "Short, one-step actions paired with recognisable visual cues reduce the demand for dense text.", languageTitle: "Language-aware support", languageBody: "Website text changes to the language the student chooses, alongside language-aware Read Aloud.", personTitle: "A real person when needed", personBody: "Students can choose a simple path to human SAS support without completing a long written explanation.",
  extensionKicker: "Chrome + Edge extension", extensionTitle: "Small controls. A clearer page.", extensionBody: "The extension is the continuity layer, not the whole product. It carries a student’s selected reading, focus, contrast, and read-aloud tools from Under Progress into the wider web. Saved presets remain available after the browser closes.", read: "Read", focus: "Focus", listen: "Listen", download: "Download extension", github: "View on GitHub",
  projectKicker: "Support Under Progress", projectTitle: "Help make the project better.", projectBody: "You can support the project without sharing payment details here: share it, star the repository, or report a barrier that needs attention.", starTitle: "Star and share", starBody: "Help other people find the project.", barrierTitle: "Report a barrier", barrierBody: "Tell us where a page or flow needs work.", testTitle: "Test the tools", testBody: "Real feedback helps guide the next improvement.",
  setupKicker: "Your accessibility account", setupTitle: "Build a profile that fits you.", setupBody: "Changes affect the sample text below. Connect the extension to carry your saved preset to regular webpages.", profileProgress: "Profile progress", choices: "choices", editable: "Your settings remain editable from this page and the extension.", needsTitle: "Choose support needs", needsBody: "Choose any number of options. The list is compact so it does not take over your screen.", profileName: "Profile name", profilePlaceholder: "For example: My study profile", showMore: "Show more choices", showFewer: "Show fewer choices", defaultTitle: "Set your default", defaultBody: "These controls change the sample preview, not the rest of the website.", presetName: "Preset name", defaultPreset: "My everyday web", textSize: "Text size", lineSpacing: "Line spacing", compact: "Compact", comfortable: "Comfortable", large: "Large", tight: "Tight", balanced: "Balanced", relaxed: "Relaxed", highContrast: "High contrast", contrastBody: "Strengthen the sample contrast.", focusSupport: "Focus support", focusBody: "Highlight only the sample reading area.", on: "On", off: "Off", sampleLabel: "Live sample text", previewOnly: "Preview only", sampleTitle: "A quiet place to begin", sampleBodyOne: "This sample changes as you choose text size, line spacing, contrast, and focus support. The rest of the setup page stays stable, so you can compare changes comfortably.", sampleBodyTwo: "You can revise your profile later from the website or from the extension while you browse another webpage.",
  connectSave: "Connect and save", installExtension: "Install the extension, then choose Connect extension.", checkingExtension: "Checking for the Under Progress extension…", connectedExtension: "Extension connected. Changes can now be sent to it.", importedExtension: "Current extension settings were imported.", staleExtension: "The extension was updated or reloaded. Reload this webpage, then connect again.", unavailableExtension: "We could not reach the extension. If you just installed, updated, or reloaded it, reload this webpage and try again.", connectExtension: "Connect extension", refreshExtension: "Refresh extension connection", saveAsDefault: "Save as default", defaultSaved: "Default saved", reset: "Reset", sendSettings: "Send current settings to extension", connectFirst: "Connect the extension first, then send your settings.", sendingSettings: "Sending current settings to the extension…", savedToExtension: "Preset “{name}” is saved in the extension and set as default.", savedOnDevice: "Your profile is saved on this device. Connect the extension to send it.", resetDone: "Your website and extension controls were reset.",
  languageFloating: "Language", languageKicker: "Language and listening", languagePromptTitle: "Is {language} your language?", languagePromptBody: "Choose the language you want Under Progress to use across this website and remember for Read Aloud. This uses your browser language as a hint, not your IP address or location.", languageNotice: "This choice changes the website text and controls the Read Aloud voice in the Under Progress Chrome and Edge extension. Read Aloud uses only a matching installed voice. If your device has no matching voice, it shows an instruction instead of silently switching to English or your browser default.", languageLabel: "Choose your language", languageSaved: "{language} saved for this website and extension Read Aloud.", languageError: "Your browser could not save this language. Please allow local storage and try again.", useLanguage: "Use {language}", saved: "{language} saved", close: "Close", notNow: "Not now", notFound: "This page is not here.", returnHome: "Return to Under Progress",
  optionAdhd: "ADHD", optionAutism: "Autism spectrum", optionDyslexia: "Dyslexia", optionDyscalculia: "Dyscalculia", optionDyspraxia: "Dyspraxia", optionLowVision: "Low vision or blindness", optionColorVision: "Color vision difference", optionHearing: "Deaf or hard of hearing", optionSpeech: "Speech or language difference", optionLearning: "Learning disability", optionMemory: "Memory or executive function", optionMotor: "Motor or mobility disability", optionChronic: "Chronic illness or fatigue", optionAnxiety: "Anxiety or sensory overwhelm", optionOther: "Another support need", optionPreferNot: "Prefer not to say",
};

const arabic: Record<string, string> = {
  ...english,
  pageTitle: "Under Progress — الويب يجب أن يتكيف مع الناس", pageDescription: "Under Progress رفيق إتاحة للطلبة قائم على الموافقة، يساعد الطلبة على جعل الويب أسهل للقراءة والفهم والتركيز.", navHow: "كيف يعمل", navSupport: "دعم الطلبة", navExtension: "الإضافة", navProject: "دعم المشروع", chooseTools: "اختر أدواتك", createProfile: "أنشئ ملفك", exploreJourney: "استكشف الرحلة", dark: "داكن", light: "فاتح", useDark: "استخدم الوضع الداكن", useLight: "استخدم الوضع الفاتح", back: "رجوع",
  heroKicker: "رفيق إتاحة للطلبة قائم على الموافقة", heroTitle: "لنجعل التعلّم أسهل وصولاً.", heroBody: "يساعد Under Progress الطلبة على وصف ما يدعمهم، والتعلّم في بيئة ميسّرة، والوصول إلى الدعم البشري المناسب، مع حمل أدواتهم المختارة إلى ما بعد الفصل الدراسي.", heroNote: "اختياراتك ملكك · دعم لا تشخيص",
  howKicker: "كيف يعمل", howTitle: "اختياراتك ترافقك.", howBody: "يبدأ ملفك بمعاينة واضحة، ثم يصبح إعداد إتاحة محفوظاً، ويمكن استخدامه خارج مساحة التعلّم من خلال الإضافة.", chooseSupport: "اختر الدعم", chooseSupportBody: "اختر حاجة دعم واحدة أو أكثر في قائمة مختصرة للهاتف والكمبيوتر.", seeSample: "شاهد نموذجاً", seeSampleBody: "يتغير حجم النص والتباعد والتباين والتركيز في منطقة قراءة نموذجية ثابتة.", saveDefault: "احفظ إعداداً افتراضياً", saveDefaultBody: "احتفظ بنقطة بداية للجلسات القادمة وغيّرها عندما تتغير احتياجاتك.", reachSupport: "اطلب الدعم", reachSupportBody: "استخدم الإضافة لأدوات عملية واطلب إرشاداً بشرياً عندما تختار.",
  coreKicker: "التجربة الأساسية", coreTitle: "تعلّم بدعم، وفق شروطك.", coreBody: "Under Progress هو تجربة للتعلّم والدعم، وليس مجرد إضافة لتغيير الخط. يتيح للطلبة اختيار أدوات مفيدة والتأمل فيما ينجح واتخاذ قرار طلب إرشاد خدمات إتاحة الطلبة (SAS).", coreNote: "لا إحالات تلقائية. لا ادعاءات تشخيصية. لا إجراء من دون موافقة الطالب.", learn: "تعلّم", learnTitle: "أدوات تعلّم ميسّرة", learnBody: "يستخدم الطلبة إعدادات القراءة والتركيز والتباين والاستماع التي تساعدهم على التفاعل مع مواد التعلّم.", checkIn: "تفقّد", checkTitle: "تأمل اختياري", checkBody: "تساعد المتابعات القصيرة الطالب على ملاحظة ما يفيده وتحديث دعمه المختار مع الوقت.", connect: "تواصل", connectTitle: "دعم بشري بالاختيار", connectBody: "عندما يكون مستعداً، يستطيع الطالب طلب إرشاد SAS. يقدم الشخص، لا الخوارزمية، الدعم.",
  beyondKicker: "ما بعد النص", beyondTitle: "مسار واضح لا يعتمد على القراءة.", beyondBody: "يُصمَّم Under Progress للطلبة الذين لا يستطيعون، أو لا يفضّلون، الاعتماد على نموذج مليء بالنص. ينبغي أن تكون رحلة الدعم قابلة للاستخدام عبر الاستماع والإشارات المرئية والمسار البشري، لا عبر التعليمات المكتوبة فقط.", voiceTitle: "إرشاد يبدأ بالصوت", voiceBody: "يمكن سماع الإرشادات البسيطة ومحتوى التعلّم بدلاً من قراءته فقط.", iconTitle: "اختيارات تقودها الأيقونات", iconBody: "تقلل الإجراءات القصيرة بخطوة واحدة مع إشارات مرئية معروفة من عبء النص الكثيف.", languageTitle: "دعم واعٍ باللغة", languageBody: "يتغير نص الموقع إلى اللغة التي يختارها الطالب مع القراءة بصوت عالٍ الواعية باللغة.", personTitle: "شخص حقيقي عند الحاجة", personBody: "يستطيع الطلبة اختيار مسار بسيط لدعم SAS البشري من دون شرح كتابي طويل.",
  extensionKicker: "إضافة Chrome وEdge", extensionTitle: "تحكم بسيط. صفحة أوضح.", extensionBody: "الإضافة طبقة استمرارية وليست المنتج كله. تحمل أدوات القراءة والتركيز والتباين والقراءة بصوت عالٍ التي اختارها الطالب إلى الويب الأوسع. تبقى الإعدادات المحفوظة متاحة بعد إغلاق المتصفح.", read: "اقرأ", focus: "ركّز", listen: "استمع", download: "نزّل الإضافة", github: "اعرض على GitHub",
  projectKicker: "ادعم Under Progress", projectTitle: "ساعد في تحسين المشروع.", projectBody: "يمكنك دعم المشروع من دون مشاركة بيانات دفع هنا: شاركه أو ضع نجمة للمستودع أو أبلغ عن حاجز يحتاج إلى اهتمام.", starTitle: "ضع نجمة وشارك", starBody: "ساعد الآخرين على العثور على المشروع.", barrierTitle: "أبلغ عن حاجز", barrierBody: "أخبرنا أين يحتاج مسار أو صفحة إلى تحسين.", testTitle: "اختبر الأدوات", testBody: "تساعدنا الملاحظات الواقعية على توجيه التحسين التالي.",
  setupKicker: "حساب الإتاحة الخاص بك", setupTitle: "أنشئ ملفاً يناسبك.", setupBody: "تؤثر التغييرات في النص النموذجي أدناه. صِل الإضافة لنقل إعدادك المحفوظ إلى صفحات الويب العادية.", profileProgress: "تقدّم الملف", choices: "اختيارات", editable: "تبقى إعداداتك قابلة للتعديل من هذه الصفحة والإضافة.", needsTitle: "اختر احتياجات الدعم", needsBody: "اختر أي عدد من الخيارات. القائمة مختصرة حتى لا تسيطر على الشاشة.", profileName: "اسم الملف", profilePlaceholder: "مثال: ملف دراستي", showMore: "أظهر مزيداً من الخيارات", showFewer: "أظهر خيارات أقل", defaultTitle: "عيّن إعدادك الافتراضي", defaultBody: "تغيّر هذه الأدوات المعاينة فقط، وليس بقية الموقع.", presetName: "اسم الإعداد", defaultPreset: "ويبّي اليومي", textSize: "حجم النص", lineSpacing: "تباعد الأسطر", compact: "مضغوط", comfortable: "مريح", large: "كبير", tight: "ضيق", balanced: "متوازن", relaxed: "مريح", highContrast: "تباين عالٍ", contrastBody: "عزّز تباين العينة.", focusSupport: "دعم التركيز", focusBody: "أبرز منطقة القراءة النموذجية فقط.", on: "تشغيل", off: "إيقاف", sampleLabel: "نص نموذجي مباشر", previewOnly: "معاينة فقط", sampleTitle: "مكان هادئ للبدء", sampleBodyOne: "تتغير هذه العينة عند اختيار حجم النص وتباعد الأسطر والتباين ودعم التركيز. تبقى بقية صفحة الإعداد مستقرة لتتمكن من المقارنة براحة.", sampleBodyTwo: "يمكنك تعديل ملفك لاحقاً من الموقع أو الإضافة أثناء تصفح صفحة أخرى.",
  connectSave: "صِل واحفظ", installExtension: "ثبّت الإضافة ثم اختر صِل الإضافة.", checkingExtension: "جارٍ البحث عن إضافة Under Progress…", connectedExtension: "تم الاتصال بالإضافة. يمكنك الآن إرسال التغييرات إليها.", importedExtension: "تم استيراد إعدادات الإضافة الحالية.", staleExtension: "تم تحديث الإضافة أو إعادة تحميلها. أعد تحميل صفحة الويب هذه ثم اتصل مرة أخرى.", unavailableExtension: "لم نتمكن من الوصول إلى الإضافة. إذا ثبّتّها أو حدّثتها أو أعدت تحميلها للتو، فأعد تحميل صفحة الويب هذه وحاول مرة أخرى.", connectExtension: "صِل الإضافة", refreshExtension: "حدّث اتصال الإضافة", saveAsDefault: "احفظ كإعداد افتراضي", defaultSaved: "تم حفظ الإعداد", reset: "إعادة تعيين", sendSettings: "أرسل الإعدادات الحالية إلى الإضافة", connectFirst: "صِل الإضافة أولاً ثم أرسل إعداداتك.", sendingSettings: "جارٍ إرسال الإعدادات الحالية إلى الإضافة…", savedToExtension: "تم حفظ الإعداد “{name}” في الإضافة وتعيينه افتراضياً.", savedOnDevice: "تم حفظ ملفك على هذا الجهاز. صِل الإضافة لإرساله.", resetDone: "تمت إعادة تعيين أدوات الموقع والإضافة.",
  languageFloating: "اللغة", languageKicker: "اللغة والاستماع", languagePromptTitle: "هل {language} لغتك؟", languagePromptBody: "اختر اللغة التي تريد أن يستخدمها Under Progress في هذا الموقع ويتذكرها للقراءة بصوت عالٍ. يستخدم ذلك لغة متصفحك كتلميح، وليس عنوان IP أو موقعك.", languageNotice: "يغيّر هذا الاختيار نص الموقع ويتحكم بصوت القراءة بصوت عالٍ في إضافة Under Progress لـ Chrome وEdge. تستخدم القراءة بصوت عالٍ صوتاً مثبتاً مطابقاً فقط. إذا لم يكن لدى جهازك صوت مطابق، تظهر تعليمات بدلاً من التبديل بصمت إلى الإنجليزية أو الإعداد الافتراضي للمتصفح.", languageLabel: "اختر لغتك", languageSaved: "تم حفظ {language} لهذا الموقع وللقراءة بصوت عالٍ في الإضافة.", languageError: "تعذر على المتصفح حفظ هذه اللغة. يرجى السماح بالتخزين المحلي والمحاولة مجدداً.", useLanguage: "استخدم {language}", saved: "تم حفظ {language}", close: "إغلاق", notNow: "ليس الآن", notFound: "هذه الصفحة غير موجودة.", returnHome: "العودة إلى Under Progress",
  optionAdhd: "اضطراب فرط الحركة وتشتت الانتباه", optionAutism: "طيف التوحّد", optionDyslexia: "عسر القراءة", optionDyscalculia: "عسر الحساب", optionDyspraxia: "عسر الأداء", optionLowVision: "ضعف البصر أو العمى", optionColorVision: "اختلاف رؤية الألوان", optionHearing: "الصمم أو ضعف السمع", optionSpeech: "اختلاف الكلام أو اللغة", optionLearning: "صعوبة تعلّم", optionMemory: "الذاكرة أو الوظيفة التنفيذية", optionMotor: "إعاقة حركية أو تنقل", optionChronic: "مرض مزمن أو إرهاق", optionAnxiety: "قلق أو إرهاق حسي", optionOther: "حاجة دعم أخرى", optionPreferNot: "أفضل عدم الإفصاح",
};

const simplifiedChinese: Record<string, string> = {
  ...english,
  pageTitle: "Under Progress — 网络应当适应每个人", pageDescription: "Under Progress 是以同意为先的学生无障碍伙伴，帮助学生更轻松地阅读、理解和专注于网页内容。", navHow: "使用方式", navSupport: "学生支持", navExtension: "扩展程序", navProject: "支持项目", chooseTools: "选择你的工具", createProfile: "创建个人资料", exploreJourney: "了解流程", dark: "深色", light: "浅色", useDark: "使用深色模式", useLight: "使用浅色模式", back: "返回",
  heroKicker: "以同意为先的学生无障碍伙伴", heroTitle: "让学习更容易获得支持。", heroBody: "Under Progress 帮助学生说明哪些支持对自己有用，在无障碍环境中学习，并联系合适的人工支持，同时把自己选择的工具带到课堂之外。", heroNote: "你的选择由你决定 · 提供支持，不作诊断",
  howKicker: "使用方式", howTitle: "你的选择会跟着你。", howBody: "你的个人资料从清晰的示例预览开始，成为已保存的无障碍预设，并可通过扩展程序在学习空间之外使用。", chooseSupport: "选择支持", chooseSupportBody: "在适用于手机和桌面的紧凑列表中选择一项或多项支持需要。", seeSample: "查看示例", seeSampleBody: "文字大小、间距、对比度和专注支持会在稳定的示例阅读区中更新。", saveDefault: "保存默认设置", saveDefaultBody: "为未来会话保留一个起点，并在需求变化时随时修改。", reachSupport: "获得支持", reachSupportBody: "在你选择时使用扩展程序的实用工具并请求人工指导。",
  coreKicker: "核心体验", coreTitle: "以适合自己的方式获得支持。", coreBody: "Under Progress 是学习与支持体验，而不只是改变字体的扩展程序。学生可以选择有用工具、反思哪些方法有效，并决定是否寻求学生无障碍服务（SAS）人工指导。", coreNote: "没有自动转介。没有诊断性声明。未经学生同意不采取行动。", learn: "学习", learnTitle: "无障碍学习工具", learnBody: "学生使用阅读、专注、对比度和聆听设置，更好地参与学习材料。", checkIn: "检查", checkTitle: "可选反思", checkBody: "简短的检查帮助学生注意到哪些方法有帮助，并随着时间更新自己选择的支持。", connect: "联系", connectTitle: "由学生选择的人工支持", connectBody: "准备好时，学生可以选择请求 SAS 指导。提供支持的是人，而不是算法。",
  beyondKicker: "不止文字", beyondTitle: "一条不依赖阅读的清晰路径。", beyondBody: "Under Progress 正在为无法或不愿依赖大量文字表单的学生设计。支持流程应可通过聆听、视觉提示和人工途径使用，而不仅是书面说明。", voiceTitle: "语音优先指导", voiceBody: "简单提示和学习内容可以被朗读，而不只靠阅读。", iconTitle: "图标引导选择", iconBody: "带有熟悉视觉提示的简短单步操作可减轻密集文字的负担。", languageTitle: "语言感知支持", languageBody: "网站文字会变为学生选择的语言，并配合语言感知的朗读功能。", personTitle: "需要时找到真人", personBody: "学生可以选择简单途径获得人工 SAS 支持，而无需完成冗长的书面说明。",
  extensionKicker: "Chrome 和 Edge 扩展程序", extensionTitle: "小小控制，更清晰的页面。", extensionBody: "扩展程序是连续性层，而不是整个产品。它将学生在 Under Progress 中选择的阅读、专注、对比度和朗读工具带到更广泛的网页中。已保存的预设在关闭浏览器后仍可使用。", read: "阅读", focus: "专注", listen: "聆听", download: "下载扩展程序", github: "在 GitHub 查看",
  projectKicker: "支持 Under Progress", projectTitle: "帮助项目变得更好。", projectBody: "你可以在这里不分享付款信息的情况下支持项目：分享它、给仓库加星，或报告需要关注的障碍。", starTitle: "加星并分享", starBody: "帮助更多人找到项目。", barrierTitle: "报告障碍", barrierBody: "告诉我们哪个页面或流程需要改进。", testTitle: "测试工具", testBody: "真实反馈能帮助指引下一次改进。",
  setupKicker: "你的无障碍账户", setupTitle: "建立适合你的个人资料。", setupBody: "更改只影响下方示例文字。连接扩展程序即可将已保存预设带到普通网页。", profileProgress: "个人资料进度", choices: "项选择", editable: "你可以从本页和扩展程序继续编辑设置。", needsTitle: "选择支持需要", needsBody: "可选择任意数量的选项。列表保持紧凑，不会占满你的屏幕。", profileName: "个人资料名称", profilePlaceholder: "例如：我的学习资料", showMore: "显示更多选项", showFewer: "显示更少选项", defaultTitle: "设置默认值", defaultBody: "这些控制只改变示例预览，不改变网站其余部分。", presetName: "预设名称", defaultPreset: "我的日常网页", textSize: "文字大小", lineSpacing: "行距", compact: "紧凑", comfortable: "舒适", large: "大", tight: "紧密", balanced: "平衡", relaxed: "宽松", highContrast: "高对比度", contrastBody: "增强示例对比度。", focusSupport: "专注支持", focusBody: "只突出显示示例阅读区。", on: "开启", off: "关闭", sampleLabel: "实时示例文字", previewOnly: "仅预览", sampleTitle: "安静的开始之处", sampleBodyOne: "当你选择文字大小、行距、对比度和专注支持时，此示例会发生变化。设置页其余部分保持稳定，让你可以舒适地比较变化。", sampleBodyTwo: "之后，你可以在浏览其他网页时从网站或扩展程序修改个人资料。",
  connectSave: "连接并保存", installExtension: "安装扩展程序，然后选择“连接扩展程序”。", checkingExtension: "正在检查 Under Progress 扩展程序…", connectedExtension: "扩展程序已连接。现在可以向它发送更改。", importedExtension: "已导入当前扩展程序设置。", staleExtension: "扩展程序已更新或重新加载。请重新加载此网页，然后再次连接。", unavailableExtension: "无法连接到扩展程序。如果你刚刚安装、更新或重新加载它，请重新加载此网页后重试。", connectExtension: "连接扩展程序", refreshExtension: "刷新扩展程序连接", saveAsDefault: "保存为默认值", defaultSaved: "默认值已保存", reset: "重置", sendSettings: "向扩展程序发送当前设置", connectFirst: "请先连接扩展程序，然后发送设置。", sendingSettings: "正在向扩展程序发送当前设置…", savedToExtension: "预设“{name}”已保存到扩展程序并设为默认值。", savedOnDevice: "你的个人资料已保存在此设备上。连接扩展程序即可发送。", resetDone: "你的网站和扩展程序控制已重置。",
  languageFloating: "语言", languageKicker: "语言与聆听", languagePromptTitle: "{language} 是你的语言吗？", languagePromptBody: "选择你希望 Under Progress 在整个网站使用并为朗读记住的语言。它使用浏览器语言作为提示，而不是你的 IP 地址或位置。", languageNotice: "此选择会更改网站文字，并控制 Under Progress Chrome 和 Edge 扩展程序中的朗读语音。朗读只使用已安装的匹配语音。如果设备没有匹配语音，它会显示说明，而不会悄悄切换到英语或浏览器默认语音。", languageLabel: "选择你的语言", languageSaved: "已将 {language} 保存用于本网站和扩展程序朗读。", languageError: "浏览器无法保存此语言。请允许本地存储后重试。", useLanguage: "使用 {language}", saved: "已保存 {language}", close: "关闭", notNow: "暂不", notFound: "此页面不存在。", returnHome: "返回 Under Progress",
  optionAdhd: "注意力缺陷多动障碍", optionAutism: "自闭症谱系", optionDyslexia: "阅读障碍", optionDyscalculia: "计算障碍", optionDyspraxia: "动作协调困难", optionLowVision: "低视力或失明", optionColorVision: "色觉差异", optionHearing: "聋或听力障碍", optionSpeech: "言语或语言差异", optionLearning: "学习障碍", optionMemory: "记忆或执行功能", optionMotor: "运动或行动障碍", optionChronic: "慢性疾病或疲劳", optionAnxiety: "焦虑或感官过载", optionOther: "其他支持需要", optionPreferNot: "不愿透露",
};

const traditionalChinese: Record<string, string> = { ...simplifiedChinese,
  navHow: "使用方式", navSupport: "學生支援", navExtension: "擴充功能", navProject: "支援專案", chooseTools: "選擇你的工具", createProfile: "建立個人資料", exploreJourney: "了解流程", dark: "深色", light: "淺色", useDark: "使用深色模式", useLight: "使用淺色模式", back: "返回",
  pageTitle: "Under Progress — 網路應當適應每個人", pageDescription: "Under Progress 是以同意為先的學生無障礙夥伴，幫助學生更輕鬆地閱讀、理解和專注於網頁內容。", heroKicker: "以同意為先的學生無障礙夥伴", heroTitle: "讓學習更容易獲得支援。", heroBody: "Under Progress 幫助學生說明哪些支援對自己有用，在無障礙環境中學習，並聯絡合適的人工支援，同時把自己選擇的工具帶到課堂之外。", heroNote: "你的選擇由你決定 · 提供支援，不作診斷",
  howTitle: "你的選擇會跟著你。", howBody: "你的個人資料從清晰的示例預覽開始，成為已儲存的無障礙預設，並可透過擴充功能在學習空間之外使用。", chooseSupport: "選擇支援", chooseSupportBody: "在適用於手機和桌面的精簡清單中選擇一項或多項支援需要。", seeSample: "查看示例", seeSampleBody: "文字大小、間距、對比度和專注支援會在穩定的示例閱讀區中更新。", saveDefault: "儲存預設", saveDefaultBody: "為未來工作階段保留一個起點，並在需求變化時隨時修改。", reachSupport: "取得支援", reachSupportBody: "在你選擇時使用擴充功能的實用工具並請求人工指導。",
  coreKicker: "核心體驗", coreTitle: "以適合自己的方式獲得支援。", coreBody: "Under Progress 是學習與支援體驗，而不只是改變字型的擴充功能。學生可以選擇有用工具、反思哪些方法有效，並決定是否尋求學生無障礙服務（SAS）人工指導。", coreNote: "沒有自動轉介。沒有診斷性聲明。未經學生同意不採取行動。", learn: "學習", learnTitle: "無障礙學習工具", learnBody: "學生使用閱讀、專注、對比度和聆聽設定，更好地參與學習材料。", checkIn: "檢查", checkTitle: "可選反思", checkBody: "簡短的檢查幫助學生注意到哪些方法有幫助，並隨著時間更新自己選擇的支援。", connect: "聯絡", connectTitle: "由學生選擇的人工支援", connectBody: "準備好時，學生可以選擇請求 SAS 指導。提供支援的是人，而不是演算法。",
  beyondKicker: "不只文字", beyondTitle: "一條不依賴閱讀的清晰路徑。", beyondBody: "Under Progress 正在為無法或不願依賴大量文字表單的學生設計。支援流程應可透過聆聽、視覺提示和人工途徑使用，而不僅是書面說明。", voiceTitle: "語音優先指導", voiceBody: "簡單提示和學習內容可以被朗讀，而不只靠閱讀。", iconTitle: "圖示引導選擇", iconBody: "帶有熟悉視覺提示的簡短單步操作可減輕密集文字的負擔。", languageTitle: "語言感知支援", languageBody: "網站文字會變為學生選擇的語言，並配合語言感知的朗讀功能。", personTitle: "需要時找到真人", personBody: "學生可以選擇簡單途徑獲得人工 SAS 支援，而無需完成冗長的書面說明。"
};

const messages: Record<SiteLanguage, Record<string, string>> = { en: english, ar: arabic, "zh-CN": simplifiedChinese, "zh-TW": traditionalChinese };
function resolveLanguage(value?: string | null): SiteLanguage {
  const normalized = (value || "").toLowerCase();
  if (normalized.startsWith("ar")) return "ar";
  if (normalized.startsWith("zh")) return /tw|hk|mo/.test(normalized) ? "zh-TW" : "zh-CN";
  return "en";
}
function fill(template: string, values?: Record<string, string>) { return template.replace(/\{(\w+)\}/g, (_match, key) => values?.[key] ?? ""); }
export function extensionLanguageMessage(language: string) { return { source: "under-progress-website", type: "set-language", language: resolveLanguage(language) }; }

type LanguageContextValue = { language: SiteLanguage; direction: "ltr" | "rtl"; t: (key: string, values?: Record<string, string>) => string; setLanguage: (language: string) => SiteLanguage; languageLabel: (language: string) => string; };
const LanguageContext = createContext<LanguageContextValue | null>(null);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<SiteLanguage>("en");
  useEffect(() => { const saved = window.localStorage.getItem(languageStorageKey); const detected = navigator.languages?.[0] || navigator.language; setLanguageState(resolveLanguage(saved || detected)); }, []);
  const setLanguage = (next: string) => { const normalized = resolveLanguage(next); const saved = saveLanguagePreference(window.localStorage, normalized); setLanguageState(resolveLanguage(saved)); window.postMessage(extensionLanguageMessage(normalized), window.location.origin); return normalized; };
  const direction = language === "ar" ? "rtl" : "ltr";
  useEffect(() => { document.documentElement.lang = language; document.documentElement.dir = direction; document.title = messages[language].pageTitle; document.querySelector('meta[name="description"]')?.setAttribute("content", messages[language].pageDescription); }, [direction, language]);
  const value = useMemo<LanguageContextValue>(() => ({ language, direction, t: (key, values) => fill(messages[language][key] || english[key] || key, values), setLanguage, languageLabel: (value) => siteLanguageOptions.find(option => option.code === resolveLanguage(value))?.label || value }), [direction, language]);
  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() { const value = useContext(LanguageContext); if (!value) throw new Error("useLanguage must be used within LanguageProvider"); return value; }
export { resolveLanguage };
