/** Under Progress public page — consent first, user-led choices, and portable accessibility tools. */
import { ArrowRight, BookOpen, Check, CircleHelp, Focus, HandHeart, Headphones, Menu, MoveRight, Sparkles, Type, X } from "lucide-react";
import { useState } from "react";
import { useLocation } from "wouter";
import { ThemeToggle } from "../components/ThemeToggle";
import { useLanguage } from "../lib/i18n";
import { useTheme } from "../lib/useTheme";

const heroAsset = "/assets/under-progress-hero.png";
const extensionAsset = "/assets/under-progress-extension.png";
const logoAsset = "/assets/under-progress-logo.png";
const extensionDownloadUrl = "https://github.com/ZeruxUAE/under-progress-extension/releases/latest/download/under-progress-extension.zip";
const extensionRepoUrl = "https://github.com/ZeruxUAE/under-progress-extension";
export default function Home() {
  const [, setLocation] = useLocation(); const [menuOpen, setMenuOpen] = useState(false); const { dark, toggleTheme } = useTheme(); const { t } = useLanguage();
  const goSetup = () => setLocation("/setup"); const scrollTo = (id: string) => document.getElementById(id)?.scrollIntoView({ behavior: "smooth", block: "start" });
  const nav = (id: string, label: string) => <button onClick={() => { scrollTo(id); setMenuOpen(false); }}>{label}</button>;
  return <main className="theme-shell profile-shell overflow-x-hidden"><header className="sticky top-0 z-40 border-b border-[var(--line)] bg-[var(--paper)]/94 backdrop-blur"><div className="mx-auto flex max-w-[1400px] items-center justify-between px-5 py-4 sm:px-8 lg:px-12"><button type="button" onClick={() => scrollTo("top")} className="flex items-center gap-3 text-left"><img src={logoAsset} alt="Under Progress" className="h-10 w-10 object-contain" /><span className="brand-ink font-serif text-xl font-semibold tracking-[-.045em]">Under Progress</span></button><nav className="hidden items-center gap-6 text-sm font-bold lg:flex">{nav("how-it-works", t("navHow"))}{nav("student-support", t("navSupport"))}{nav("extension", t("navExtension"))}{nav("support", t("navProject"))}<ThemeToggle dark={dark} onToggle={toggleTheme} /><button onClick={goSetup} className="rounded-full bg-[#0F8B7B] px-5 py-2.5 text-white">{t("chooseTools")}</button></nav><div className="flex items-center gap-2 lg:hidden"><ThemeToggle dark={dark} onToggle={toggleTheme} /><button aria-label="Open navigation" onClick={() => setMenuOpen(!menuOpen)} className="light-button rounded-full border border-[var(--line)] p-2">{menuOpen ? <X /> : <Menu />}</button></div></div>{menuOpen && <div className="theme-panel mx-4 mb-4 rounded-2xl p-4 lg:hidden"><div className="flex flex-col gap-3 text-sm font-bold">{nav("how-it-works", t("navHow"))}{nav("student-support", t("navSupport"))}{nav("extension", t("navExtension"))}<button onClick={goSetup} className="rounded-full bg-[#0F8B7B] px-4 py-3 text-white">{t("chooseTools")}</button></div></div>}</header>
    <section id="top" className="mx-auto grid max-w-[1400px] gap-12 px-5 py-16 sm:px-8 lg:grid-cols-2 lg:px-12 lg:py-24"><div className="flex flex-col justify-center"><div className="field-label mb-6">{t("heroKicker")}</div><h1 className="display-title max-w-[10ch] text-5xl leading-[.92] sm:text-7xl">{t("heroTitle")}</h1><p className="theme-muted mt-7 max-w-[56ch] text-base sm:text-lg">{t("heroBody")}</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><button onClick={goSetup} className="rounded-full bg-[#0F8B7B] px-6 py-3.5 text-sm font-bold text-white">{t("createProfile")} <MoveRight className="ml-1 inline h-4 w-4" /></button><button onClick={() => scrollTo("student-support")} className="light-button rounded-full border border-[var(--line)] px-6 py-3.5 text-sm font-bold">{t("exploreJourney")}</button></div><p className="theme-muted mt-5 font-mono text-[10px] uppercase tracking-[.12em]">{t("heroNote")}</p></div><div className="relative"><div className="soft-card absolute inset-4 rounded-[40px]" /><img src={heroAsset} alt="Student using a laptop" className="relative w-full rounded-[32px] object-cover shadow-[0_28px_72px_rgba(16,42,67,.18)]" /></div></section>
    <section id="how-it-works" className="border-y border-[var(--line)] bg-[var(--paper-deep)] py-16"><div className="mx-auto grid max-w-[1400px] gap-10 px-5 sm:px-8 lg:grid-cols-[.8fr_1.2fr] lg:px-12"><div><div className="field-label mb-5">{t("howKicker")}</div><h2 className="display-title max-w-[9ch] text-5xl leading-[.95]">{t("howTitle")}</h2><p className="theme-muted mt-6 max-w-[38ch]">{t("howBody")}</p></div><div className="grid gap-5 sm:grid-cols-2">{[["01", "chooseSupport", "chooseSupportBody"], ["02", "seeSample", "seeSampleBody"], ["03", "saveDefault", "saveDefaultBody"], ["04", "reachSupport", "reachSupportBody"]].map(([number, title, body]) => <article key={number} className="theme-panel rounded-[24px] p-6"><span className="font-mono text-[#0F8B7B]">{number}</span><h3 className="mt-5 text-xl font-bold">{t(title)}</h3><p className="theme-muted mt-3 text-sm">{t(body)}</p></article>)}</div></div></section>
    <section id="student-support" className="mx-auto max-w-[1400px] px-5 py-20 sm:px-8 lg:px-12"><div className="grid gap-10 lg:grid-cols-[.7fr_1.3fr]"><div><div className="field-label mb-5">{t("coreKicker")}</div><h2 className="display-title max-w-[10ch] text-5xl leading-[.95]">{t("coreTitle")}</h2><p className="theme-muted mt-6 max-w-[41ch]">{t("coreBody")}</p><p className="mt-5 max-w-[41ch] text-sm font-semibold text-[#0F8B7B]">{t("coreNote")}</p></div><div className="grid gap-5 sm:grid-cols-3"><article className="theme-panel rounded-[24px] p-6"><BookOpen className="h-7 w-7 text-[#0F8B7B]" /><span className="mt-6 block font-mono text-[#0F8B7B]">01 · {t("learn").toUpperCase()}</span><h3 className="mt-4 text-xl font-bold">{t("learnTitle")}</h3><p className="theme-muted mt-3 text-sm">{t("learnBody")}</p></article><article className="theme-panel rounded-[24px] p-6"><Check className="h-7 w-7 text-[#F3B945]" /><span className="mt-6 block font-mono text-[#0F8B7B]">02 · {t("checkIn").toUpperCase()}</span><h3 className="mt-4 text-xl font-bold">{t("checkTitle")}</h3><p className="theme-muted mt-3 text-sm">{t("checkBody")}</p></article><article className="theme-panel rounded-[24px] p-6"><HandHeart className="h-7 w-7 text-[#0F8B7B]" /><span className="mt-6 block font-mono text-[#0F8B7B]">03 · {t("connect").toUpperCase()}</span><h3 className="mt-4 text-xl font-bold">{t("connectTitle")}</h3><p className="theme-muted mt-3 text-sm">{t("connectBody")}</p></article></div></div><div className="mt-12 border-y border-[var(--line)] py-10"><div className="grid gap-8 lg:grid-cols-[.82fr_1.18fr]"><div><div className="field-label mb-5">{t("beyondKicker")}</div><h3 className="display-title max-w-[12ch] text-4xl leading-[.96]">{t("beyondTitle")}</h3><p className="theme-muted mt-5 max-w-[43ch]">{t("beyondBody")}</p></div><div className="grid gap-4 sm:grid-cols-2"><article className="rounded-[20px] bg-[#E3F3EF] p-5 dark:bg-[#163D3A]"><Headphones className="h-6 w-6 text-[#0F8B7B]" /><h4 className="mt-5 font-bold">{t("voiceTitle")}</h4><p className="theme-muted mt-2 text-sm">{t("voiceBody")}</p></article><article className="rounded-[20px] bg-[#FCF1CF] p-5 dark:bg-[#4B3B17]"><CircleHelp className="h-6 w-6 text-[#A66C00]" /><h4 className="mt-5 font-bold">{t("iconTitle")}</h4><p className="theme-muted mt-2 text-sm">{t("iconBody")}</p></article><article className="rounded-[20px] bg-[#E8EFF7] p-5 dark:bg-[#1B334A]"><Type className="h-6 w-6 text-[#0F8B7B]" /><h4 className="mt-5 font-bold">{t("languageTitle")}</h4><p className="theme-muted mt-2 text-sm">{t("languageBody")}</p></article><article className="rounded-[20px] bg-[#F0EAF7] p-5 dark:bg-[#39244C]"><HandHeart className="h-6 w-6 text-[#75409B]" /><h4 className="mt-5 font-bold">{t("personTitle")}</h4><p className="theme-muted mt-2 text-sm">{t("personBody")}</p></article></div></div></div></section>
    <section id="extension" className="bg-[#102A43] py-20 text-white"><div className="mx-auto grid max-w-[1400px] items-center gap-12 px-5 sm:px-8 lg:grid-cols-2 lg:px-12"><div><div className="field-label mb-5 !text-[#F3B945]">{t("extensionKicker")}</div><h2 className="display-title max-w-[12ch] text-5xl leading-[.95] !text-white">{t("extensionTitle")}</h2><p className="mt-6 max-w-[54ch] text-white/75">{t("extensionBody")}</p><div className="mt-8 grid grid-cols-3 gap-3"><div className="rounded-2xl border border-white/15 bg-white/5 p-4"><Type className="h-6 w-6 text-[#F3B945]" /><p className="mt-4 text-sm font-bold">{t("read")}</p></div><div className="rounded-2xl border border-white/15 bg-white/5 p-4"><Focus className="h-6 w-6 text-[#F3B945]" /><p className="mt-4 text-sm font-bold">{t("focus")}</p></div><div className="rounded-2xl border border-white/15 bg-white/5 p-4"><Headphones className="h-6 w-6 text-[#F3B945]" /><p className="mt-4 text-sm font-bold">{t("listen")}</p></div></div><div className="mt-8 flex flex-col gap-3 sm:flex-row"><a href={extensionDownloadUrl} className="rounded-full bg-[#F3B945] px-6 py-3.5 text-center text-sm font-bold text-[#102A43]">{t("download")} <ArrowRight className="ml-1 inline h-4 w-4" /></a><a href={extensionRepoUrl} target="_blank" rel="noreferrer" className="rounded-full border border-white/30 px-6 py-3.5 text-center text-sm font-bold">{t("github")}</a></div></div><img src={extensionAsset} alt="Under Progress extension" className="w-full rounded-[30px] border border-white/10" /></div></section>
    <section id="support" className="mx-auto max-w-[1400px] px-5 py-20 sm:px-8 lg:px-12"><div className="grid gap-10 lg:grid-cols-[.72fr_1.28fr]"><div><div className="field-label mb-5">{t("projectKicker")}</div><h2 className="display-title max-w-[10ch] text-5xl leading-[.95]">{t("projectTitle")}</h2><p className="theme-muted mt-6 max-w-[40ch]">{t("projectBody")}</p></div><div className="grid gap-5 sm:grid-cols-3"><a href={extensionRepoUrl} target="_blank" rel="noreferrer" className="theme-panel rounded-[22px] p-6"><Sparkles className="h-7 w-7 text-[#0F8B7B]" /><h3 className="mt-6 text-lg font-bold">{t("starTitle")}</h3><p className="theme-muted mt-2 text-sm">{t("starBody")}</p></a><a href={`${extensionRepoUrl}/issues`} target="_blank" rel="noreferrer" className="theme-panel rounded-[22px] p-6"><CircleHelp className="h-7 w-7 text-[#F3B945]" /><h3 className="mt-6 text-lg font-bold">{t("barrierTitle")}</h3><p className="theme-muted mt-2 text-sm">{t("barrierBody")}</p></a><button onClick={goSetup} className="theme-panel rounded-[22px] p-6 text-left"><Check className="h-7 w-7 text-[#0F8B7B]" /><h3 className="mt-6 text-lg font-bold">{t("testTitle")}</h3><p className="theme-muted mt-2 text-sm">{t("testBody")}</p></button></div></div></section>
  </main>;
}
