/** Under Progress — compact, live account setup that applies every choice to the full website. */
import { ArrowLeft, Check, ChevronDown, Contrast, Focus, PlugZap, RotateCcw, Send, Type } from "lucide-react";
import { useEffect, useMemo, useRef, useState } from "react";
import { Link, useLocation } from "wouter";
import { ThemeToggle } from "../components/ThemeToggle";
import { useTheme } from "../lib/useTheme";

const logoAsset = "/assets/under-progress-logo.png";
const extensionDownloadUrl = "https://github.com/ZeruxUAE/under-progress-extension/releases/latest/download/under-progress-extension.zip";
const options = [
  ["adhd","ADHD"],["autism","Autism spectrum"],["dyslexia","Dyslexia"],["dyscalculia","Dyscalculia"],["dyspraxia","Dyspraxia"],["low-vision","Low vision or blindness"],["color-vision","Color vision difference"],["hearing","Deaf or hard of hearing"],["speech-language","Speech or language difference"],["learning","Learning disability"],["memory","Memory or executive function"],["motor","Motor or mobility disability"],["chronic","Chronic illness or fatigue"],["anxiety","Anxiety or sensory overwhelm"],["other","Another support need"],["prefer-not","Prefer not to say"],
] as const;
type Profile = { displayName:string; disabilities:string[]; presetName:string; textSize:"Compact"|"Comfortable"|"Large"; spacing:"Tight"|"Balanced"|"Relaxed"; contrast:boolean; focus:boolean; };
type ExtensionSettings = { textScale:number; lineSpacing:number; readingWidth:number; contrast:boolean; focus:boolean; };
const initial: Profile = { displayName:"", disabilities:[], presetName:"My everyday web", textSize:"Comfortable", spacing:"Balanced", contrast:false, focus:false };
const toExtension = (profile:Profile):ExtensionSettings => ({ textScale:profile.textSize === "Large" ? 120 : profile.textSize === "Compact" ? 90 : 100, lineSpacing:profile.spacing === "Relaxed" ? 1.8 : profile.spacing === "Tight" ? 1.2 : 1.5, readingWidth:70, contrast:profile.contrast, focus:profile.focus });
const fromExtension = (settings:ExtensionSettings,current:Profile):Profile => ({...current,textSize:settings.textScale>=115?"Large":settings.textScale<=95?"Compact":"Comfortable",spacing:settings.lineSpacing>=1.7?"Relaxed":settings.lineSpacing<=1.3?"Tight":"Balanced",contrast:Boolean(settings.contrast),focus:Boolean(settings.focus)});
function SamplePreview({ profile }: { profile: Profile }) { const scale = profile.textSize === "Large" ? "text-lg" : profile.textSize === "Compact" ? "text-sm" : "text-base"; const lineHeight = profile.spacing === "Relaxed" ? 2.15 : profile.spacing === "Tight" ? 1.15 : 1.55; return <section className={`relative overflow-hidden rounded-2xl border p-5 transition-colors ${profile.contrast ? "border-white bg-[#102A43] text-white" : "border-[var(--line)] bg-[var(--paper-deep)]"}`}><div className="mb-4 flex items-center justify-between"><span className={`field-label ${profile.contrast ? "!text-[#F3B945]" : ""}`}>Live sample text</span><span className="font-mono text-[10px] opacity-70">PREVIEW ONLY</span></div>{profile.focus && <div className="absolute inset-x-4 top-12 bottom-4 rounded-xl border-2 border-[#0F8B7B] bg-[#D9F3ED]/20"/>}<article className={`relative max-w-[65ch] ${scale}`}><h3 className="font-serif text-2xl font-semibold" style={{ lineHeight: 1.1 }}>A quiet place to begin</h3><p className="mt-3" style={{ lineHeight }}>This sample changes as you choose text size, line spacing, contrast, and focus support. The rest of the setup page stays stable, so you can compare changes comfortably.</p><p className="mt-3" style={{ lineHeight }}>You can revise your profile later from the website or from the extension while you browse another webpage.</p></article></section>}

export default function Setup(){
  const [,setLocation]=useLocation(); const {dark,toggleTheme}=useTheme(); const [profile,setProfile]=useState<Profile>(initial); const [showAll,setShowAll]=useState(false); const [saved,setSaved]=useState(false); const [connected,setConnected]=useState(false); const [message,setMessage]=useState("Install the extension, then choose Connect extension."); const [ready,setReady]=useState(false); const skipSync=useRef(false);
  useEffect(()=>{const stored=window.localStorage.getItem("under-progress-profile");if(stored)setProfile({...initial,...JSON.parse(stored)});setReady(true)},[]);
  useEffect(()=>{const receive=(event:MessageEvent)=>{if(event.origin!==window.location.origin||event.source!==window||event.data?.source!=="under-progress-extension")return;if(event.data.type==="connection-status"){setConnected(true);setMessage("Extension connected. Changes can now be sent to it.")}if(event.data.type==="extension-profile"&&event.data.settings){skipSync.current=true;setConnected(true);setProfile(current=>({...fromExtension(event.data.settings,current),...(event.data.profile||{})}));setMessage("Current extension settings were imported.")}if(event.data.type==="preset-saved"){setConnected(true);setMessage(`Preset “${event.data.presetName || "Website default"}” is saved in the extension and set as default.`)}};const request=()=>window.postMessage({source:"under-progress-website",type:"request-profile"},window.location.origin);window.addEventListener("message",receive);[0,350,900,1800].forEach(delay=>window.setTimeout(request,delay));return()=>window.removeEventListener("message",receive)},[]);
  const publish=(next=profile)=>window.postMessage({source:"under-progress-website",type:"save-profile",settings:toExtension(next),profile:{displayName:next.displayName,disabilities:next.disabilities,presetName:next.presetName}},window.location.origin);
  useEffect(()=>{if(!ready)return;window.localStorage.setItem("under-progress-profile",JSON.stringify(profile));if(connected&&skipSync.current)skipSync.current=false},[profile,ready,connected]);
  const selected=profile.disabilities.length; const visible=showAll?options:options.slice(0,6); const progress=useMemo(()=>Math.min(100,(Number(selected>0)+Number(profile.textSize!=="Comfortable")+Number(profile.spacing!=="Balanced")+Number(profile.contrast)+Number(profile.focus))*20),[profile,selected]);
  const toggle=(id:string)=>setProfile(current=>({...current,disabilities:current.disabilities.includes(id)?current.disabilities.filter(item=>item!==id):[...current.disabilities,id]}));
  const connect=()=>{setMessage("Checking for the Under Progress extension…");[0,350,900,1800,3000].forEach(delay=>window.setTimeout(()=>window.postMessage({source:"under-progress-website",type:"request-profile"},window.location.origin),delay))};
  const save=()=>{window.localStorage.setItem("under-progress-profile",JSON.stringify(profile));if(connected)publish(profile);setSaved(true);setMessage(connected?"Preset saved. The extension will confirm when it receives it.":"Your profile is saved on this device. Connect the extension to send it.");window.setTimeout(()=>setSaved(false),2200)};
  const reset=()=>{setProfile(initial);window.localStorage.removeItem("under-progress-profile");publish(initial);setMessage("Your website and extension controls were reset.")};
  return <main className="theme-shell relative"><header className="border-b border-[var(--line)] bg-[var(--paper)]/94 backdrop-blur"><div className="mx-auto flex max-w-[1280px] items-center justify-between px-5 py-4 sm:px-8"><Link href="/" className="flex items-center gap-3"><img src={logoAsset} alt="Under Progress mark" className="h-10 w-10"/><span className="brand-ink font-serif text-xl font-semibold">Under Progress</span></Link><div className="flex items-center gap-2"><ThemeToggle dark={dark} onToggle={toggleTheme}/><button onClick={()=>setLocation("/")} className="light-button inline-flex items-center gap-2 rounded-full border border-[var(--line)] px-4 py-2 text-sm font-bold"><ArrowLeft className="h-4 w-4"/>Back</button></div></div></header>
  <section className="mx-auto grid max-w-[1280px] gap-8 px-5 py-8 sm:px-8 lg:grid-cols-[.65fr_1.35fr] lg:py-14"><aside className="lg:sticky lg:top-8 lg:self-start"><div className="field-label mb-5">Your accessibility account</div><h1 className="display-title max-w-[9ch] text-5xl leading-[.92]">Build a profile that fits you.</h1><p className="theme-muted mt-6 max-w-[35ch] text-sm">Changes affect the sample text below. Connect the extension to carry your saved preset to regular webpages.</p><div className="theme-panel mt-8 rounded-2xl p-5"><div className="flex justify-between"><span className="field-label">Profile progress</span><span className="font-mono text-[#0F8B7B]">{selected} choices</span></div><div className="mt-4 h-2 rounded-full bg-[var(--paper-deep)]"><div className="h-full rounded-full bg-[#0F8B7B] transition-[width]" style={{width:`${progress}%`}}/></div><p className="theme-muted mt-4 text-xs">Your settings remain editable from this page and the extension.</p></div></aside>
  <div className="space-y-6"><section className="theme-panel rounded-[26px] p-5 sm:p-7"><div className="mb-6 flex items-start gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-full bg-[#D9F3ED] font-mono text-sm text-[#0F8B7B]">01</span><div><h2 className="text-xl font-bold">Choose support needs</h2><p className="theme-muted mt-1 text-sm">Choose any number of options. The list is compact so it does not take over your screen.</p></div></div><label className="block text-sm font-bold">Profile name<input value={profile.displayName} onChange={event=>setProfile(current=>({...current,displayName:event.target.value}))} className="mt-2 w-full rounded-xl border border-[var(--line)] px-4 py-3" placeholder="For example: My study profile"/></label><div className="mt-5 grid max-h-[290px] gap-2 overflow-y-auto pr-1 sm:grid-cols-2">{visible.map(([id,label])=><button type="button" key={id} onClick={()=>toggle(id)} aria-pressed={profile.disabilities.includes(id)} className={`flex items-center justify-between rounded-xl border px-3 py-3 text-left text-sm font-bold ${profile.disabilities.includes(id)?"border-[#0F8B7B] bg-[#D9F3ED] text-[#102A43]":"light-button border-[var(--line)]"}`}><span>{label}</span>{profile.disabilities.includes(id)&&<Check className="h-4 w-4 text-[#0F8B7B]"/>}</button>)}</div><button type="button" onClick={()=>setShowAll(current=>!current)} className="mt-4 inline-flex items-center gap-2 text-sm font-bold text-[#0F8B7B]">{showAll?"Show fewer choices":`Show ${options.length-visible.length} more choices`}<ChevronDown className={`h-4 w-4 transition-transform ${showAll?"rotate-180":""}`}/></button></section>
  <section className="theme-panel rounded-[26px] p-5 sm:p-7"><div className="mb-6 flex items-start gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-full bg-[#FCE9B7] font-mono text-sm text-[#9B6600]">02</span><div><h2 className="text-xl font-bold">Set your default</h2><p className="theme-muted mt-1 text-sm">These controls change the sample preview, not the rest of the website.</p></div></div><label className="block text-sm font-bold">Preset name<input value={profile.presetName} onChange={event=>setProfile(current=>({...current,presetName:event.target.value}))} className="mt-2 w-full rounded-xl border border-[var(--line)] px-4 py-3"/></label><div className="mt-6 grid gap-5 sm:grid-cols-2"><div><p className="mb-3 flex items-center gap-2 text-sm font-bold"><Type className="h-4 w-4 text-[#0F8B7B]"/>Text size</p><div className="flex flex-wrap gap-2">{(["Compact","Comfortable","Large"] as const).map(value=><button key={value} onClick={()=>setProfile(current=>({...current,textSize:value}))} className={`rounded-full px-4 py-2 text-xs font-bold ${profile.textSize===value?"bg-[#102A43] text-white":"light-button border border-[var(--line)]"}`}>{value}</button>)}</div></div><div><p className="mb-3 text-sm font-bold">Line spacing</p><div className="flex flex-wrap gap-2">{(["Tight","Balanced","Relaxed"] as const).map(value=><button key={value} onClick={()=>setProfile(current=>({...current,spacing:value}))} className={`rounded-full px-4 py-2 text-xs font-bold ${profile.spacing===value?"bg-[#102A43] text-white":"light-button border border-[var(--line)]"}`}>{value}</button>)}</div></div><button onClick={()=>setProfile(current=>({...current,contrast:!current.contrast}))} className={`light-button flex items-center justify-between rounded-xl border p-4 text-left ${profile.contrast?"border-[#0F8B7B] bg-[#D9F3ED] text-[#102A43]":"border-[var(--line)]"}`}><span><b className="block text-sm"><Contrast className="mr-2 inline h-4 w-4"/>High contrast</b><small className="theme-muted">Strengthen the sample contrast.</small></span><span>{profile.contrast?"On":"Off"}</span></button><button onClick={()=>setProfile(current=>({...current,focus:!current.focus}))} className={`light-button flex items-center justify-between rounded-xl border p-4 text-left ${profile.focus?"border-[#0F8B7B] bg-[#D9F3ED] text-[#102A43]":"border-[var(--line)]"}`}><span><b className="block text-sm"><Focus className="mr-2 inline h-4 w-4"/>Focus support</b><small className="theme-muted">Highlight only the sample reading area.</small></span><span>{profile.focus?"On":"Off"}</span></button></div><div className="mt-6"><SamplePreview profile={profile}/></div></section>
  <section className="theme-panel rounded-[26px] p-5 sm:p-7"><div className="mb-5 flex items-start gap-3"><PlugZap className="mt-0.5 h-5 w-5 text-[#0F8B7B]"/><div><h2 className="text-xl font-bold">Connect and save</h2><p className="theme-muted mt-1 text-sm">{message}</p></div></div><div className="flex flex-col gap-3 sm:flex-row"><button onClick={connect} className="light-button rounded-full border border-[var(--line)] px-5 py-3 text-sm font-bold">{connected?"Refresh extension connection":"Connect extension"}</button><a href={extensionDownloadUrl} className="rounded-full bg-[#102A43] px-5 py-3 text-center text-sm font-bold text-white">Download extension</a><button onClick={save} className="rounded-full bg-[#0F8B7B] px-5 py-3 text-sm font-bold text-white">{saved?"Default saved":"Save as default"}</button><button onClick={reset} className="light-button rounded-full border border-[var(--line)] px-5 py-3 text-sm font-bold"><RotateCcw className="mr-1 inline h-4 w-4"/>Reset</button></div><button onClick={()=>{publish();setMessage(connected?"Sending current settings to the extension…":"Connect the extension first, then send your settings.")}} disabled={!connected} className="mt-4 inline-flex items-center gap-1 text-sm font-bold text-[#0F8B7B] disabled:cursor-not-allowed disabled:opacity-50"><Send className="h-4 w-4"/>Send current settings to extension</button></section></div></section></main>
}
